import type { Metadata } from "next";
import { Geist, Geist_Mono, Inknut_Antiqua } from "next/font/google";
// @ts-ignore ignore error
import "./globals.css";
import ClientProviders from "./ClientProviders";
import FirebaseAuthProvider from "./FirebaseAuthProvider";

// Define fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inknut = Inknut_Antiqua({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inknut",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inknut.variable} antialiased`}>
        <FirebaseAuthProvider>
          <ClientProviders>
            {children}
          </ClientProviders>
        </FirebaseAuthProvider>
      </body>
    </html>
  );
}
